### ISSUE TITLE
Broken test: KillsProcessOnSigInt

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/DotNetTools#444] opened 2018-05-24 19:39 UTC
This test [fails](http://aspnetci/viewLog.html?buildId=474382&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR) occasionally with the following error:
```
System.TimeoutException : The operation at /_/test/dotnet-watch.FunctionalTests/NoDepsAppTests.cs:45 timed out after reaching the limit of 30000ms.
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber)
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.NoDepsAppTests.KillsProcessOnSigInt() in /_/test/dotnet-watch.FunctionalTests/NoDepsAppTests.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
The temporary test folder is /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/watm1qqi.1rp
Copying project /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/TestProjects/NoDepsApp to /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/watm1qqi.1rp/NoDepsApp
Restoring msbuild project in NoDepsApp
Project directory: '/mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/watm1qqi.1rp/NoDepsApp'
Started process 15865: /mnt/work/33bdfc1cae7b2a38/.dotnet/dotnet restore
  Restoring packages for /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/watm1qqi.1rp/NoDepsApp/NoDepsApp.csproj...
  Generating MSBuild file /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/watm1qqi.1rp/NoDepsApp/obj/NoDepsApp.csproj.nuget.g.props.
  Generating MSBuild file /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/watm1qqi.1rp/NoDepsApp/obj/NoDepsApp.csproj.nuget.g.targets.
  Restore completed in 268.56 ms for /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/watm1qqi.1rp/NoDepsApp/NoDepsApp.csproj.
Process exited 15865
Process exited 15865 with code 0
Building NoDepsApp
Project directory: '/mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/watm1qqi.1rp/NoDepsApp'
Started process 16148: /mnt/work/33bdfc1cae7b2a38/.dotnet/dotnet build
Microsoft (R) Build Engine version 15.7.177.53362 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
  Restore completed in 56.44 ms for /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/watm1qqi.1rp/NoDepsApp/NoDepsApp.csproj.
  You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452
  NoDepsApp -> /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/watm1qqi.1rp/NoDepsApp/bin/Release/netcoreapp2.2/NoDepsApp.dll
Build succeeded.
    0 Warning(s)
    0 Error(s)
Time Elapsed 00:00:03.40
Process exited 16148
Process exited 16148 with code 0
5/24/18 5:07:37 PM: process start: '/mnt/work/33bdfc1cae7b2a38/.dotnet/dotnet /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tool/dotnet-watch.dll run -- --no-exit'
Waiting for output line [msg == 'Started']. Will wait for 120 sec.
5/24/18 5:07:37 PM: post: 'watch : Running MSBuild target 'GenerateWatchList' on '/mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/watm1qqi.1rp/NoDepsApp/NoDepsApp.csproj''
5/24/18 5:07:37 PM: recv: 'watch : Running MSBuild target 'GenerateWatchList' on '/mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/watm1qqi.1rp/NoDepsApp/NoDepsApp.csproj''
5/24/18 5:07:37 PM: post: 'watch : Started '/mnt/work/33bdfc1cae7b2a38/.dotnet/dotnet' with process id 16504'
5/24/18 5:07:37 PM: recv: 'watch : Started '/mnt/work/33bdfc1cae7b2a38/.dotnet/dotnet' with process id 16504'
5/24/18 5:07:38 PM: post: 'watch : Process id 16504 ran for 1493ms'
5/24/18 5:07:38 PM: recv: 'watch : Process id 16504 ran for 1493ms'
5/24/18 5:07:38 PM: post: 'watch : Watching 2 file(s) for changes'
5/24/18 5:07:38 PM: recv: 'watch : Watching 2 file(s) for changes'
5/24/18 5:07:38 PM: post: 'watch : Started '/mnt/work/33bdfc1cae7b2a38/.dotnet/dotnet' with process id 16706'
5/24/18 5:07:38 PM: recv: 'watch : Started '/mnt/work/33bdfc1cae7b2a38/.dotnet/dotnet' with process id 16706'
5/24/18 5:07:38 PM: post: 'watch : Running dotnet with the following arguments: run -- --no-exit'
5/24/18 5:07:38 PM: post: 'watch : Started'
5/24/18 5:07:38 PM: recv: 'watch : Running dotnet with the following arguments: run -- --no-exit'
5/24/18 5:07:38 PM: recv: 'watch : Started'
5/24/18 5:07:39 PM: post: 'Telemetry is: Disabled'
5/24/18 5:07:39 PM: recv: 'Telemetry is: Disabled'
5/24/18 5:07:42 PM: post: 'Running dotnet exec "/mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/watm1qqi.1rp/NoDepsApp/bin/Release/netcoreapp2.2/NoDepsApp.dll" --no-exit'
5/24/18 5:07:42 PM: recv: 'Running dotnet exec "/mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/watm1qqi.1rp/NoDepsApp/bin/Release/netcoreapp2.2/NoDepsApp.dll" --no-exit'
5/24/18 5:07:42 PM: post: 'Process ID: 17060'
5/24/18 5:07:42 PM: recv: 'Process ID: 17060'
5/24/18 5:07:43 PM: post: 'Started'
5/24/18 5:07:43 PM: recv: 'Started'
5/24/18 5:07:43 PM: post: 'PID = 17060'
Waiting for output line [msg.StartsWith('PID =')]. Will wait for 30 sec.
5/24/18 5:07:43 PM: recv: 'PID = 17060'
kill -SIGINT 16485
kill -SIGINT 17060
Disposing WatchableApp
5/24/18 5:08:13 PM: post: 'watch : Process id 16706 ran for 34318ms'
```

This test seems to fail 100% of the time on Ubuntu.

**Comment by natemcmaster** [comment] 2018-05-24 21:20
> This test seems to fail 100% of the time on Ubuntu.

I'm going to 'upgrade' this from flaky to bug then.

**Comment by tmds** [comment] 2018-05-31 08:31
Two possible causes:
- https://github.com/dotnet/corefx/issues/29699
- https://github.com/dotnet/coreclr/pull/15393

If it's the first, you need the bugfix (2.1.1) or a workaround.
If it's the second, your test should use SIGTERM.

**Comment by natemcmaster** [comment] 2018-05-31 08:35
Funny enough, this test was added to reproduce https://github.com/dotnet/corefx/issues/29699 and verify the workaround added in https://github.com/aspnet/DotNetTools/pull/438. But since this will be fixed in the runtime, it's probably better to just remove this test. I'm not sure why sending `kill -SIGINT` doesn't work well on some Linux agents.

**Comment by tmds** [comment] 2018-05-31 08:51
> I'm not sure why sending kill -SIGINT doesn't work well on some Linux agents.

SIGINT is the thing you get when a user does Ctrl+C. It's meant to interrupt the program in some way, usually implemented to terminate it.
When the program is not started interactively, a user can't be pressing that. So a shell will configure that signal to be ignored, to avoid accidentally terminating a background process. I changed .NET Core to respect that ignore.
If your intent is to terminate, SIGTERM and SIGKILL is what you should be using.
If you want to test SIGINT specifically, try `set -m` to enable job control.

**Closed** 2018-06-01 03:16 UTC
Labels: bug
