### ISSUE TITLE
Broken test: RestartProcessThatTerminatesAfterFileChange on High Sierra

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/DotNetTools#407] opened 2018-03-16 18:52 UTC
```
System.TimeoutException : The operation at /_/test/dotnet-watch.FunctionalTests/AwaitableProcess.cs:68 timed out after reaching the limit of 30000ms.
[03:53:52]	   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.AwaitableProcess.GetOutputLineAsync(String message, TimeSpan timeout) in /_/test/dotnet-watch.FunctionalTests/AwaitableProcess.cs:line 68
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.NoDepsAppTests.RestartProcessThatTerminatesAfterFileChange() in /_/test/dotnet-watch.FunctionalTests/NoDepsAppTests.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
```

This tests fails High Sierra builds [every time](http://aspnetci/viewType.html?buildTypeId=XPlat_HighSierraOsxUniverse).

**Comment by ryanbrandenburg** [comment] 2018-03-27 16:37
@JunTaoLuo said he was going to do the initial investigation here, suspects it's an SDK issue.

**Comment by muratg** [comment] 2018-03-28 21:41
@JunTaoLuo Moved out of the milestone, but if we get to it I don't mind.

**Comment by natemcmaster** [comment] 2018-03-28 22:16
I think there may be a real product issue. See #416

**Comment by JunTaoLuo** [comment] 2018-03-28 23:19
Yea this one shouldn't be moved out of the milestone

**Comment by ryanbrandenburg** [comment] 2018-03-29 18:11
I assume based off @natemcmaster  and @JunTaoLuo's comments that this not being in the 2.1.0-preview2 milestone was an oversight.

**Comment by JunTaoLuo** [comment] 2018-03-30 02:13
Took some time to investigate this today and on my local machine the test is flaky instead of just broken. It definitely is a product issue though since it is consistently flaky after we updated the SDK version. I wasn't able to track down the root cause though. @natemcmaster I noticed that you have done some work here so in case I still don't get anywhere with my investigations tonight can you take a look while I'm off on vacation?

**Comment by natemcmaster** [comment] 2018-03-30 06:48
I'll take a look

**Comment by natemcmaster** [comment] 2018-03-31 00:04
Since this corresponds to an SDK update, I suspect it may be another side effect of node reuse, which was the big thing to land recently in the SDK. I couldn't reproduce locally, so it might just be a CI issue. Regardless, let's disable nodeReuse inside dotnet-watch until we can investigate more.: https://github.com/aspnet/DotNetTools/pull/418

**Comment by natemcmaster** [comment] 2018-04-02 17:36
Should be fixed in https://github.com/aspnet/DotNetTools/pull/419. I verified the flakiness on my computer and that https://github.com/aspnet/DotNetTools/pull/419 fixed it. I'll keep an eye on CI and will re-open if the tests is still failing.

**Comment by natemcmaster** [comment] 2018-04-18 16:38
Still flaky. http://aspnetci/viewLog.html?buildId=449723&tab=buildResultsDiv&buildTypeId=Releases_21Public_UbuntuUniverse

```
System.TimeoutException : The operation at /_/test/dotnet-watch.FunctionalTests/AwaitableProcess.cs:68 timed out after reaching the limit of 30000ms.
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.AwaitableProcess.GetOutputLineAsync(String message, TimeSpan timeout) in /_/test/dotnet-watch.FunctionalTests/AwaitableProcess.cs:line 68
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.NoDepsAppTests.RestartProcessThatTerminatesAfterFileChange() in /_/test/dotnet-watch.FunctionalTests/NoDepsAppTests.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
The temporary test folder is /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/fdhvnksz.rdx
Copying project /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/TestProjects/NoDepsApp to /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/fdhvnksz.rdx/NoDepsApp
Restoring msbuild project in NoDepsApp
Project directory: '/mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/fdhvnksz.rdx/NoDepsApp'
Started process 126362: /mnt/work/33bdfc1cae7b2a38/.dotnet/dotnet restore
  Restoring packages for /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/fdhvnksz.rdx/NoDepsApp/NoDepsApp.csproj...
  Generating MSBuild file /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/fdhvnksz.rdx/NoDepsApp/obj/NoDepsApp.csproj.nuget.g.props.
  Generating MSBuild file /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/fdhvnksz.rdx/NoDepsApp/obj/NoDepsApp.csproj.nuget.g.targets.
  Restore completed in 297.47 ms for /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/fdhvnksz.rdx/NoDepsApp/NoDepsApp.csproj.


Process exited 126362
Process exited 126362 with code 0
Building NoDepsApp
Project directory: '/mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/fdhvnksz.rdx/NoDepsApp'
Started process 126480: /mnt/work/33bdfc1cae7b2a38/.dotnet/dotnet build
Microsoft (R) Build Engine version 15.7.145.53551 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 53.03 ms for /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/fdhvnksz.rdx/NoDepsApp/NoDepsApp.csproj.
  You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452
  NoDepsApp -> /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tmp/fdhvnksz.rdx/NoDepsApp/bin/Release/netcoreapp2.1/NoDepsApp.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.96


Process exited 126480
Process exited 126480 with code 0
4/18/18 12:58:10 AM: process start: '/mnt/work/33bdfc1cae7b2a38/.dotnet/dotnet /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.1/tool/dotnet-watch.dll run --'
Waiting for output line [msg == 'Started']. Will wait for 120 sec.
4/18/18 12:58:11 AM: post: 'watch : Started'
4/18/18 12:58:11 AM: recv: 'watch : Started'
4/18/18 12:58:14 AM: post: 'Started'
4/18/18 12:58:14 AM: post: 'PID = 126914'
4/18/18 12:58:14 AM: recv: 'Started'
4/18/18 12:58:14 AM: post: 'Exiting'
Waiting for output line [msg.StartsWith('PID =')]. Will wait for 30 sec.
4/18/18 12:58:14 AM: recv: 'PID = 126914'
Waiting for output line [msg == 'Exiting']. Will wait for 30 sec.
4/18/18 12:58:14 AM: recv: 'Exiting'
Waiting for output line [msg == 'watch : Exited']. Will wait for 30 sec.
4/18/18 12:58:14 AM: post: 'watch : Exited'
4/18/18 12:58:14 AM: recv: 'watch : Exited'
4/18/18 12:58:14 AM: post: 'watch : Waiting for a file to change before restarting dotnet...'
Waiting for output line [msg == 'Started']. Will wait for 30 sec.
4/18/18 12:58:14 AM: recv: 'watch : Waiting for a file to change before restarting dotnet...'
Disposing WatchableApp
```

**Comment by natemcmaster** [comment] 2018-05-04 01:50
Fixed in https://github.com/aspnet/DotNetTools/commit/3193f45bae62c2dd2b0867e6efe26cce8f3738ce

**Closed by natemcmaster** 2018-05-04 01:50 UTC
Labels: investigate
