### ISSUE TITLE
Version for package 'Microsoft.DotNet.Watcher.Tools' could not be resolved when running inside a Docker container

### ISSUE THREAD

**Issue by shiitake** [aspnet/DotNetTools#300] opened 2017-05-30 17:07 UTC
I'm attempting to use dotnet watch in a console application running in docker but I'm getting errors when trying to get dotnet watch to work. 

I'm running Windows 10, Visual Studio 2017

```xml
<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
<OutputType>Exe</OutputType>
<TargetFramework>netcoreapp1.1</TargetFramework>
<RootNamespace>MyApp</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="1.0.1" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.2" />
    <PackageReference Include="newtonsoft.json" Version="10.0.2" />
    <PackageReference Include="rabbitmq.client" Version="4.1.3" />
  </ItemGroup>
</Project>
```
And here is what my Dockerfile looks like

```bash
FROM microsoft/dotnet:1.1.2-sdk

COPY . /app
WORKDIR /app

ENV USE_POLLING_FILE_WATCHER=1

RUN ["dotnet", "restore"]
RUN ["dotnet", "build"]
RUN ["dotnet", "publish", "-c", "Release", "-o", "out"]
```
I run my docker app with the command
`docker run -it --name MyApp -v //c/path/to/repo/MyApp:/app MyApp bash`

But from inside the application here when I run `dotnet watch run` I get the message: 
`Version for package `Microsoft.DotNet.Watcher.Tools` could not be resolved.`

I'm really not sure what I'm missing here. I am able to run `dotnet watch run` outside of the docker container - it only gives this message when running within the container.

**Comment by natemcmaster** [comment] 2017-05-30 18:47
Can you run `dotnet -d watch run`? 

(Taking a guess now, so let me know if the following is not true...)

Most likely, the issue is the volume-mounted `obj/project.assets.json` file, which is mounted from `C:/path/to/repo/MyApp/obj/project.assets.json`. This file would have been generated by running `dotnet restore` on your Windows host, which means it will contain a list of NuGet paths for your Windows host, not the paths to nuget packages inside the container. The .NET Core CLI uses these paths to find the Microsoft.DotNet.Watcher.Tools version when you execute `dotnet watch`.

If my guess is right, `dotnet -d watch run` will show output similar to this:
```
root@6f436fdbd010:/app# dotnet -d watch run
Telemetry is: Enabled
projectfactory: MSBUILD_EXE_PATH = /usr/share/dotnet/sdk/1.0.4/MSBuild.dll
projectfactory: MSBuild project path = /app/tools.csproj
projecttoolscommandresolver: resolving commandspec from 1 Tool Libraries.
projecttoolscommandresolver: Attempting to resolve command spec from tool Microsoft.DotNet.Watcher.Tools
projecttoolscommandresolver: nuget packages root:
- C:\Users\namc\.nuget\packages\
- C:\Users\namc\.dotnet\NuGetFallbackFolder
Microsoft.DotNet.Cli.Utils.GracefulException: Version for package `Microsoft.DotNet.Watcher.Tools` could not be resolved.
```

You can fix this by either 

 - don't mount the project folder (e.g. copy the project into a non-mounted location in the container)
 - clean the folder on Windows before mounting
 - running `dotnet restore` again within the container to regenerate `obj/project.assets.json`. (FYI dotnet restore attempts to be smart and not regenerate the file unless versions change...so you might have to `rm obj/project.assets.json` manually before running restore).

**Comment by shiitake** [comment] 2017-05-31 14:16
Thank you so much @natemcmaster - your guess was spot on and the suggested solutions worked.

**Comment by shiitake** [comment] 2017-06-15 21:25
Just wanted to update with a quick comment that running ```dotnet restore``` within the container does get past the error and allow dotnet watch to start but it breaks the intellisense in Visual Studio. 

So it sounds like I won't be able to use both dotnet watch and Visual Studio. They only way I'm able to get intellisense to work again is to kill my container and rebuild the project in Visual Studio. 

Any other options?

**Comment by natemcmaster** [comment] 2017-06-15 21:54
Essentially, VS and Docker are contending for control of `obj/MyApp.nuget.g.props`. This file contains path to the NuGet cache, which (of course) is different depending on whether you are building inside Docker or in VS.

You can make both work by removing this contention by not volume mounting your project directory. Instead, you could copy your files into the container (add a .dockerignore to exclude obj/ and bin/).

**Comment by hartmannr76** [comment] 2017-06-20 09:35
I have a solution... Will post today

**Comment by alexsandro-xpt** [comment] 2017-08-17 02:24
@hartmannr76  This not work in DotNet Core 2.0

`Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) at System.Console.set_OutputEncoding(Encoding value) at database_worker.Program.Main(String[] args) in G:\_Project01\Program.cs:line 16`

**Comment by ricky-hartmann-zocdoc** [comment] 2017-08-17 16:23
Interesting. I haven't upgraded my project yet to 2.0, but I'll do that this weekend and let you know my results. I may even put up a skeleton project on GH to show this

**Comment by hartmannr76** [comment] 2017-08-17 16:26
Interesting. I haven't upgraded my project yet to 2.0, but I'll do that this weekend and let you know my results. I may even put up a skeleton project on GH to show this

**Comment by alexsandro-xpt** [comment] 2017-08-19 02:47
@hartmannr76 I made a demo to test it, take a look https://github.com/alexsandro-xpt/WatchRunDocker/tree/dotnetcore2

**Comment by toshkuuu** [comment] 2017-08-19 12:49
@hartmannr76 Did you manage to upload the sample repo? I am also having issues with .netcore 2..

**Comment by hartmannr76** [comment] 2017-08-23 22:12
Unfortunately, the root issue seems to come from the sdk tooling, not specifically this repo. I tried running the app by itself without watcher and have the same issue.

Knowing that was the problem, I did some more digging around and the root issue seems to be because this forwards the build output to be outside of project folder. [Here is the issue tracked in sdk](https://github.com/dotnet/sdk/issues/1497) repo. This is necessary for the docker integration because you want the container to have it's own references to libraries on it's file system.

I'd be curious to see if there is a way to work around this without waiting for an sdk update.

**Comment by hartmannr76** [comment] 2017-08-28 09:07
I've found a "workaround" and forked/submitted a PR to your branch @alexsandro-xpt

**Comment by alexsandro-xpt** [comment] 2017-08-28 17:11
Perfect @hartmannr76, thank you, it will help too much some people!

**Comment by natemcmaster** [comment] 2017-08-28 17:15
> Unfortunately, the root issue seems to come from the sdk tooling, not specifically this repo. I tried running the app by itself without watcher and have the same issue.

Is there anything dotnet-watch can change to make this better? I'm aware of at least one issue I'd like fixed that may help with this (https://github.com/aspnet/DotNetTools/issues/244), but I'm curious if you found others.

**Comment by hartmannr76** [comment] 2017-08-28 17:46
That issue you're pointing out is the only thing that required a real workaround. I'll make some comments on that thread since they aren't really relevant to this. Other than that dotnet-watch is a great development asset I intend to keep using. Though app rebuild/recycle times are a bit slow and I hope [this issue eventually gets solved](https://github.com/dotnet/cli/issues/5918).

I'd say feel free to close this issue out since proposed solutions work.

**Comment by natemcmaster** [comment] 2017-08-28 19:11
Ok, I'm closing this issue for now as there isn't anything actionable here for dotnet-watch that isn't already covered by #244.

**Closed by natemcmaster** 2017-08-28 19:11 UTC
Labels: tool: watch
