### ISSUE TITLE
User secrets not working on .net core 1.0

### ISSUE THREAD

**Issue by Headspin** [aspnet/DotNetTools#207] opened 2016-10-26 20:25 UTC
When trying to run user-secrets tool I get the following error.

The specified framework 'Microsoft.NETCore.App', version '1.1.0-preview1-001100-00' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\shared\Microsoft.NETCore.App
  - The following versions are installed:
      1.0.1
  - Alternatively, install the framework version '1.1.0-preview1-001100-00'.

--------
I do not have .NET Core 1.1 Preview1 installed and I do not wish to install it, since it is still a preview version.

My project.json file points to "Microsoft.Extensions.SecretManager.Tools": "1.0.0-*". The package is restored successfuly with dotnet restore.

**Comment by moozzyk** [comment] 2016-10-26 20:34
Then you need to change the version of the package. Right now because you are using * in the version it floats to the latest 1.0.0 which is 1.0.0-preview3-final which targets 1.1.0. Specify the version as "1.0.0-preview2-final" to not to float to 1.1.

**Comment by natemcmaster** [comment] 2016-10-26 21:27
>  I do not have .NET Core 1.1 Preview1 installed and I do not wish to install it, since it is still a preview version.

The preview3-final version requires installing .NET Core 1.1 preview 1. (See https://blogs.msdn.microsoft.com/dotnet/2016/10/25/announcing-net-core-1-1-preview-1/). FWIW, .NET Core supports side-by-side installations. Installing .NET Core 1.1 won't interfere with projects using .NET Core 1.0. As @moozzyk said, use "1.0.0-preview2-final" to stick with the .NET Core 1.0 version.

Closing as this is expected behavior.

**Closed by natemcmaster** 2016-10-26 21:27 UTC
Labels: dotnet-user-secrets
