### ISSUE TITLE
dotnet watch run crashes if resource folder exists

### ISSUE THREAD

**Issue by dodyg** [aspnet/DotNetTools#222] opened 2016-11-06 21:24 UTC
```dotnet watch run``` will crash if a folder with .resx file exists. When I remove the folder, it will work fine.

I am using 1.0.0-preview2-003131

This is the source code https://github.com/dodyg/practical-aspnetcore/tree/master/localization

```
E:\GitHub\practical-aspnetcore\localization>dotnet watch run
[DotNetWatcher] info: Running dotnet with the following arguments: run
[DotNetWatcher] info: dotnet process id: 12152
Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.)) ---> System.Aggre
gateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an
 object.
   at Microsoft.DotNet.Watcher.Core.Internal.FileWatcher.<>c__DisplayClass7_0.<AddDirectoryWatcher>b__0(KeyValuePair`2 d)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.Watcher.Core.Internal.FileWatcher.AddDirectoryWatcher(String directory)
   at Microsoft.DotNet.Watcher.Core.Internal.ProjectWatcher.<WaitForChangeAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Watcher.Core.DotNetWatcher.<WaitForProjectFileToChangeAsync>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Core.DotNetWatcher.<WatchAsync>d__6.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Tools.Program.<>c__DisplayClass3_0.<MainInternal>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Watcher.Tools.Program.MainInternal(String[] args, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Tools.Program.Main(String[] args)
```

**Comment by natemcmaster** [comment] 2016-11-07 16:44
Probably a duplicate of https://github.com/aspnet/DotNetTools/issues/139. Can you try the dotnet-watch 1.0.0-preview3-final? (You'll need to install [.NET Core 1.1 preview1](https://github.com/dotnet/core/blob/master/release-notes/preview-download.md) for the preview3 version to work.)

**Comment by dodyg** [comment] 2016-11-08 13:57
Core 1.1 preview1 fixes it. Thanks.

**Closed** 2016-11-08 14:06 UTC
Labels: dotnet-watch
