### ISSUE TITLE
dotnet watch run doesn't work and doesn't provide helpful info

### ISSUE THREAD

**Issue by Monomachus** [aspnet/DotNetTools#208] opened 2016-10-31 12:15 UTC
Hello,

I'm trying to run `dotnet watch run` and it did not work, even after I specified the necessary framework.

```
C:\personal_dev\ude\roadmap_aspnet_core\helloworld>dotnet watch run -f 1.0.1
The specified framework 'Microsoft.NETCore.App', version '1.1.0-preview1-001100-
00' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\shared\Microsoft.NETCore.App
  - The following versions are installed:
      1.0.0
      1.0.0-rc2-3002702
      1.0.1
  - Alternatively, install the framework version '1.1.0-preview1-001100-00'.
```

Here's the gist of project.json file - https://gist.github.com/Monomachus/313efe5f325cd11a8f1af6d3233779f4

**Comment by natemcmaster** [comment] 2016-10-31 15:57
This is a duplicate of https://github.com/aspnet/DotNetTools/issues/207. dotnet-watch 1.0.0-preview3-final requires the 1.1.0-preview1 version of .NET Core.

**Closed** 2016-10-31 16:24 UTC
Labels: closed-duplicate
