### ISSUE TITLE
[dotnet-watch] Duplicate file entries in IDEs

### ISSUE THREAD

**Issue by bmsantos** [aspnet/DotNetTools#460] opened 2018-07-10 23:06 UTC
Watching for .cshtml file changes causes Visual Studio (and other IDEs such as Rider) to show duplicate file entries:

```xml
  <ItemGroup>
    <Watch Include="**/*.cshtml" />
  </ItemGroup>
```

https://drive.google.com/file/d/1hRzvxkuxrA1aoKjRf9StLXFmO232qCUe/view?usp=drive_web

This issue is occurring in OSX.

**Comment by natemcmaster** [comment] 2018-07-10 23:10
Try adding `Visible="false"`.

**Comment by bmsantos** [comment] 2018-07-13 13:46
This worked great to prevent duplication. The issue now is that if I add a new cshtml file to the project through the command line, this file will not be automatically detected and displayed in Visual Studio.

**Comment by bmsantos** [comment] 2018-07-17 15:36
@natemcmaster, that didn't work with Visual Studio but it did help with Rider. Also, Razor is not automatically recompiling the cshtml files. but that might be because I'm using a Blazor project.

I've notice all this because I'm creating an experimental CLI for Blazor apps ([Bionic](https://github.com/bmsantos/bionic)) that generate pages or components from the command line. 

You can recreate this issue by:

1. Installing Blazor and Blazor templates - see https://blazor.net/docs/get-started.html

2. Create a Blazor project using one of the templates: 
dotnet new blazor -o BionicApp

3. Install Bionic from NuGet: 
dotnet tool install -g Bionic

4. Init Bionic in project (this will inject watcher in csproj) - in BionicApp directory do: 
bionic start

5. Open BionicApp.csproj with Visual Studio

6. Create a new component and see it duplicated in VS: 
bionic generate component CounterComponent

**Comment by galvesribeiro** [comment] 2018-07-18 17:39
I have the exactly same issue with VS or VSCode on windows. The only files that automatically trigger the watcher build is .cs. Cshtml, html or css doesnt...

**Comment by natemcmaster** [comment] 2018-07-18 17:55
> @bmsantos: that didn't work with Visual Studio but it did help with Rider.

Which version of Visual Studio? I'm not able to reproduce with VS 15.8 Preview 4.

@galvesribeiro this is by design and is a separate from the main point of this issue. dotnet-watch only triggers a rebuild on things which affect the .dll produced, which is .cs and .resx files. In ASP.NET Core projects, you should not need to rebuild the .dll to see a html or css change since these are not part of the .dll file. Razor should respond to changes in .cshtml files without rebooting the ASP.NET Core process. If it's not working, that's a bug in Razor (cc @pranavkm).

Note: dotnet-watch does not contain specific knowledge about Blazor. I think Blazor uses .cshtml files differently than Razor, but I'm not clear on the details. If you want Blazor to support a different dotnet-watch behavior for .cshtml files, I recommend opening a bug on aspnet/Blazor, but putting that into dotnet-watch is the wrong layering.

**Comment by pranavkm** [comment] 2018-07-18 17:57
Live reloading for Blazor apps is being tracked via https://github.com/aspnet/Blazor/issues/5

**Comment by bmsantos** [comment] 2018-07-18 18:05
@natemcmaster, here are the details about my version of Visual Studio:

Visual Studio Community 2017 for Mac
Version 7.5.3 (build 7)
Installation UUID: 2c49e65f-a19c-43cf-b211-8fa92c131ecf
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.1.0
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.300
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 9.4.1 (14161)
Build 9F2000

Xamarin.Mac
Version: 4.4.1.193 (Visual Studio Community)

Xamarin.iOS
Xamarin.iOS not installed.
Can't find mtouch or the Version file at /Library/Frameworks/Xamarin.iOS.framework/Versions/Current.

Xamarin.Android
Not Installed

**Comment by natemcmaster** [comment] 2018-07-18 18:15
Oh, VS for Mac, I see. Yes, the problem reproduces there. It appears VS for Mac is incorrectly evaluating the .csproj file - they must be parsing it as raw XML, not as an MSBuild project. You can use the "Help > Report a problem" tool to report this.

In the meantime, the only workaround I can think of is to move the Watch item group into a separate file which is imported by the .csproj.
```xml
<!-- Watch.props -->
<Project>
  <ItemGroup>
    <Watch Include="**/*.cshtml" />
  </ItemGroup>
</Project>
```
```xml
<!-- MyWebApp.csproj -->
  <Import Project="Watch.props" />
```

**Comment by bmsantos** [comment] 2018-07-18 18:46
@natemcmaster, thanks for the help. The issue persists when I add .scss files to the mix:

![screen shot 2018-07-18 at 2 44 29 pm](https://user-images.githubusercontent.com/4486595/42901287-2cb63886-8a99-11e8-846f-9d64b2f8a455.png)

I'll report the problem through VS.

**Comment by bmsantos** [comment] 2018-07-18 18:53
VS Mac - Reported [issue](https://developercommunity.visualstudio.com/content/problem/296060/vs-mac-is-duplicating-files-when-watcher-is-used.html)

**Comment by natemcmaster** [comment] 2018-07-18 19:23
Ok, closing since this is something the VS for Mac team needs to address.

**Closed by natemcmaster** 2018-07-18 19:23 UTC
