### ISSUE TITLE
msbuild props (BaseIntermediateOutputPath) break dotnet watch

### ISSUE THREAD

**Issue by cbruun** [aspnet/DotNetTools#311] opened 2017-06-21 21:47 UTC
I have an ASP.NET Core website and I use dotnet watch to run it in development.

Due to my Docker setup, I place all bin and obj directories in a folder called build. To achieve this I created a Directory.Build.props with the following contents:

```xml
<Project>
  <PropertyGroup>
    <BaseOutputPath>../../build/Website/bin</BaseOutputPath>
    <BaseIntermediateOutputPath>../../build/Website/obj</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
```

This places the build artifacts in the build folder and dotnet run works. However, dotnet watch run gives me the following error:

```
$ dotnet watch run
watch : Error(s) finding watch items project file 'Website.csproj'
watch : MSBuild output from target 'GenerateWatchList':
watch : 
watch :    Build started 6/21/17 11:39:57 PM.
watch :         1>Project "/path/to/Website/Website.csproj" on node 1 (GenerateWatchList target(s)).
watch :         1>/path/to/Website/Website.csproj : error MSB4057: The target "GenerateWatchList" does not exist in the project.
watch :         1>Done Building Project "/path/to/Website/Website.csproj" (GenerateWatchList target(s)) -- FAILED.
watch :    
watch :    Build FAILED.
```

dotnet watch worked before adding the Directory.Build.props.

My csproj contains:

```xml
<ItemGroup>
  <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.0-preview1-final" />
</ItemGroup>
```

I am using .NET Core SDK version 2.0.0-preview1-005977

I apologize if this is not an actual issue and I have simply configured the watcher incorrectly. If so, any help is much appreciated.

**Comment by natemcmaster** [comment] 2017-06-21 22:05
It's a known issue. You may have noticed that dotnet-watch generated a file in `/path/to/Website/obj/Website.csproj.dotnetwatch.g.targets`. This file is what will provide the `GenerateWatchList` target. But because you've changed BaseIntermediateOutputPath, MSBuild isn't importing "project extensions" from `obj\`.  

Unfortunately, this is one of the hard problems that we don't have a good way to solve. I've added described two workarounds here: https://github.com/aspnet/DotNetTools/issues/244.

Closing as a duplicate of that issue, but let me know if those workarounds don't help.

**Closed by natemcmaster** 2017-06-21 22:05 UTC
