### ISSUE TITLE
Failed to restore package when installing

### ISSUE THREAD

**Issue by tbertenshaw** [aspnet/DotNetTools#403] opened 2018-03-05 09:41 UTC
The following error when installing `dotnet-watch`, i also get a similar error when trying to install `dotnet-user-secrets`

```powershell
PS C:\Users\Administrator> dotnet install tool --global dotnet-watch
Install failed. Failed to download package:
NuGet returned:

Failed to restore package.
WorkingDirectory:
Arguments: restore C:\Users\Administrator\AppData\Local\Temp\2\qddhiwsh.bhk\fa05i01b.zyg.csproj --runtime win10-
aseIntermediateOutputPath=\"C:\Users\Administrator\.dotnet\toolspkgs\dotnet-watch\od4zxxzc.djy\"
Output:   Restoring packages for C:\Users\Administrator\AppData\Local\Temp\2\qddhiwsh.bhk\fa05i01b.zyg.csproj...
C:\Users\Administrator\AppData\Local\Temp\2\qddhiwsh.bhk\fa05i01b.zyg.csproj : error NU1103: Unable to find a st
kage dotnet-watch with version
C:\Users\Administrator\AppData\Local\Temp\2\qddhiwsh.bhk\fa05i01b.zyg.csproj : error NU1103:   - Found 2 version
uget.org [ Nearest version: 0.0.1-alpha ]
C:\Users\Administrator\AppData\Local\Temp\2\qddhiwsh.bhk\fa05i01b.zyg.csproj : error NU1103:   - Found 1 version
:\Program Files\dotnet\sdk\NuGetFallbackFolder [ Nearest version: 2.1.0-preview1-final ]
C:\Users\Administrator\AppData\Local\Temp\2\qddhiwsh.bhk\fa05i01b.zyg.csproj : error NU1103:   - Found 0 version
ocal
C:\Users\Administrator\AppData\Local\Temp\2\qddhiwsh.bhk\fa05i01b.zyg.csproj : error NU1103:   - Found 0 version
icrosoft Visual Studio Offline Packages
C:\Users\Administrator\AppData\Local\Temp\2\qddhiwsh.bhk\fa05i01b.zyg.csproj : error NU1103:   - Found 0 version
icrosoft Azure Service Fabric SDK
C:\Users\Administrator\AppData\Local\Temp\2\qddhiwsh.bhk\fa05i01b.zyg.csproj : error NU1103:   - Found 0 version
liFallbackFolder
  Restore failed in 979.51 ms for C:\Users\Administrator\AppData\Local\Temp\2\qddhiwsh.bhk\fa05i01b.zyg.csproj.
```

Output from `dotnet --info`

```powershell
PS C:\Users\Administrator> dotnet --info
.NET Command Line Tools (2.1.300-preview1-008174)

Product Information:
 Version:            2.1.300-preview1-008174
 Commit SHA-1 hash:  b8df89a54f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26216-03
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153
```

**Comment by natemcmaster** [comment] 2018-03-05 16:38
Looks like a duplicate of https://github.com/dotnet/cli/issues/8485. To workaround, you need to specify an exact version of the package.

     dotnet install tool --global dotnet-watch --version 2.1.0-preview1-final
  
Let me know if this doesn't work and I can reopen for more investigation.

**Closed by natemcmaster** 2018-03-05 16:38 UTC
