### ISSUE TITLE
How to configure vs code debugger to use dotnet watch?

### ISSUE THREAD

**Issue by dcworldwide** [aspnet/DotNetTools#151] opened 2016-08-13 05:56 UTC
I want to run my application in debug mode, whilst using dotnet watch. 

Is it posible? If so, is it as a matter of configuring my launch settings?

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/bin/Debug/netcoreapp1.0/test-api.dll",
            "args": [],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": false,
            "launchBrowser": {
                "enabled": true,
                "args": "${auto-detect-url}",
                "windows": {
                    "command": "cmd.exe",
                    "args": "/C start ${auto-detect-url}"
                },
                "osx": {
                    "command": "open"
                },
                "linux": {
                    "command": "xdg-open"
                }
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceRoot}/Views"
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command.pickProcess}"
        }
    ]
}
```

**Comment by victorhurdugaci** [comment] 2016-08-29 21:09
Not sure if this is possible, unfortunately. The problem is that dotnet-watch is one process and it launches a dotnet process. You need the debugger to attach to the dotnet proc but you can't get that process ID easily.

Maybe @troydai has an idea?

**Comment by troydai** [comment] 2016-08-29 23:21
I don't think this is feasible. If you configure the launch.json to start the dotnet watch, the debugger is attached to the "watch" process instead of the process dotnet watch starts. Unless my understanding of how dotnet watch operates wrong.

It is tricky here. The same issue happens to dotnet test as well. In that scenario, dotnet test process itself doesn't run test. It starts another process to execute tests. That makes the launch.json unusable. We have to build specified feature to enable test debugging scenario.

**Comment by victorhurdugaci** [comment] 2016-08-29 23:36
Yeah, we'd probably have to drop a pid file or something similar to let VS code know about the actual process id. VS Code would have to understand that file though (and watch it?)

**Comment by troydai** [comment] 2016-08-30 03:22
In the case of __dotnet test__ it works because of the [protocol](https://github.com/dotnet/cli/blob/rel/1.0.0-preview2/Documentation/dotnet-test-protocol.md) it defines. The protocol allows omnisharp to communicate with dotnet cli to generate the actual start command. VS code API allows extensions to build launch configuration programmatically. So maybe this can be a feature for [OmniSharp](https://github.com/omnisharp/omnisharp-roslyn).

**Comment by victorhurdugaci** [comment] 2016-08-30 16:28
So omnisharp would need a generic protocol that any tool can implement?

**Comment by troydai** [comment] 2016-08-31 04:35
no, dotnet watch need a protocol so that omnisharp can be aware of either 1) what's that start command  therefore ask debugger to start the process; or 2) what's the eventual process ID for each newly started process.

**Comment by muratg** [comment] 2017-05-12 21:54
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Closed by muratg** 2017-05-12 21:54 UTC
Labels: dotnet-watch, question
