### ISSUE TITLE
Watch takes a long time to exit after ctrl-c

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/DotNetTools#423] opened 2018-04-05 20:55 UTC
Sdk: 2.1.300-preview2-008523
OS: macOS High-Sierra

1. `dotnet new mvc`
2. `dotnet watch -v run`
3. CTRL-C once the site is running
~30 seconds later:
```
watch : Process id 7289 ran for 34911 ms
watch : Exited with error code 128
```

**Comment by natemcmaster** [comment] 2018-04-05 21:40
Dupe of #410?

**Comment by BrennanConroy** [comment] 2018-04-05 21:44
I missed the part where he said
> I get this same behavior on Windows and macOS.

Although it is vague which behavior he is talking about...

**Comment by natemcmaster** [comment] 2018-05-04 18:38
I can't reproduce this anymore in 2.1.0-rc1. Not sure what changed, but it may have something to do with MSBuild and node reuse.

**Closed by natemcmaster** 2018-05-04 18:38 UTC
