### ISSUE TITLE
Duplicate input echo entering commands in httprepl

### ISSUE THREAD

**Issue by stuartleeks** [aspnet/DotNetTools#494] opened 2018-09-27 12:43 UTC
In the screenshot below I had typed `set base http://localhost:5000` but some of the characters were echoed to the console more than once (but not all). This makes it incredibly hard to work with the repl!

![image](https://user-images.githubusercontent.com/1824461/46146412-9eb04f00-c25a-11e8-93cf-4c00135d8abc.png)

I have just installed httprepl as per https://www.hanselman.com/blog/ and am running:
```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.401/

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  2.1.300-rc1-008673 [/usr/share/dotnet/sdk]
  2.1.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by glennc** [comment] 2018-10-09 18:17
Duplicate of: https://github.com/aspnet/DotNetTools/issues/489

**Closed by glennc** 2018-10-09 18:17 UTC
Labels: tool: httprepl
