### ISSUE TITLE
dotnet watch run says the specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.

### ISSUE THREAD

**Issue by AbhimanyuAryan** [aspnet/DotNetTools#259] opened 2017-02-03 01:18 UTC
When I run `dotnet watch run` command I get following error

  - Check application dependencies and target a framework version installed at:
      /usr/local/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.1.0
  - Alternatively, install the framework version '1.0.0'.

```
"tools": {
        "Microsoft.DotNet.Watcher.Tools": "1.0.0-preview2-final"
 },
```

```

$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
```

& when I changed project.json file to 

```
"tools": {
        "Microsoft.DotNet.Watcher.Tools": "1.1.0-preview2-final"
 },
```

& then hit `dotnet watch run` followed by `dotnet restore`. I don't see this error but then when I edit wwwroot/main.css & add background color and hit browser refresh nothing happens. I have still stop server and restart server to see the changes

**Comment by natemcmaster** [comment] 2017-02-03 02:18
Download and install .NET Core 1.0: https://www.microsoft.com/net/download/core or change to "1.1.0-preview4-final". See https://www.nuget.org/packages/Microsoft.DotNet.Watcher.Tools/ for list of available versions

**Comment by AbhimanyuAryan** [comment] 2017-02-03 04:42
@natemcmaster I have changed to `"Microsoft.DotNet.Watcher.Tools": "1.1.0-preview4-final"` but when run `dotnet watch run` & change css file & refresh browser page. Nothing happens  

Does it work only with html pages? What about css & js change or assets(images, icons) etc?

**Comment by natemcmaster** [comment] 2017-02-03 16:10
By design, dotnet watch *for project.json* won't trigger a restart of your web app when .css/.js/images etc change. Just files used by the C# compiler.

dotnet watch for MSbuild (the new thing we are working on) let's you customize which files are being watched. See https://github.com/aspnet/DotNetTools/blob/dev/src/Microsoft.DotNet.Watcher.Tools/README.md#msbuild

Re: browser doesn't show updates. Because dotnet-watch didn't restart, I would assume the issue exists when you do `dotnet run` too. Try a "hard refresh" to ensure the browser isn't caching results.

Closing the issue for now. Feel free to continue discussion. Not trying to be mean, but it seems we solve the original issue you described, and we will not longer issuing updates to the project.json version of dotnet-watch.

-Nate

**Closed by natemcmaster** 2017-02-03 16:10 UTC
Labels: question
