### ISSUE TITLE
Tools packages not compatible with x86

### ISSUE THREAD

**Issue by vsccarl** [aspnet/DotNetTools#391] opened 2018-02-05 23:31 UTC
cli build 20180202-02-1347550

On a machine with x86 build of cli installed, trying to install any built package give a variant of this:

`dotnet install tool -g dotnet-watch` 
```
Install failed. Failed to download package:
NuGet returned:
 
Failed to restore package.
WorkingDirectory:
Arguments: restore C:\Users\v-masche\AppData\Local\Temp\hc1ahsqb.yuv\azykmtii.zm3.csproj --runtime win10-x86 /p:BaseIntermediateOutputPath=\"C:\Users\v-masche\.dotnet\tools\dotnet-watch\2.1.0-preview1-28149\"
Output:   Restoring packages for C:\Users\v-masche\AppData\Local\Temp\hc1ahsqb.yuv\azykmtii.zm3.csproj...
  Installing dotnet-watch 2.1.0-preview1-28149.
C:\Users\v-masche\AppData\Local\Temp\hc1ahsqb.yuv\azykmtii.zm3.csproj : error NU1202: Package dotnet-watch 2.1.0-preview1-28149 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1) / win10-x86. Package dotnet-watch 2.1.0-preview1-28149 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any
  Restore failed in 727.35 ms for C:\Users\v-masche\AppData\Local\Temp\hc1ahsqb.yuv\azykmtii.zm3.csproj.
```

**Comment by natemcmaster** [comment] 2018-02-05 23:34
This doesn't appear to be related to bitness. This appears to be a duplicate of https://github.com/dotnet/cli/issues/8485. @vsccarl try this: 

     dotnet install tool -g dotnet-watch --version 2.1.0-preview1-28226

cc @wli3 @KathleenDollard - Any plans to improve the error messages when install fails?

**Comment by KathleenDollard** [comment] 2018-02-06 23:08
We did some work on this last week. @wli3 and @peterhuene, did we settle on that change?

**Comment by natemcmaster** [comment] 2018-02-08 16:28
Closing this as a duplicate of  dotnet/cli#8485

**Closed by natemcmaster** 2018-02-08 16:28 UTC
