### ISSUE TITLE
Is it possible for 'watch' to retain the color info from Serilog's literate console sink?

### ISSUE THREAD

**Issue by jack4it** [aspnet/DotNetTools#221] opened 2016-11-04 23:04 UTC
As discussed here https://github.com/serilog/serilog-sinks-literate/issues/13

Currently, all *pretty* colors from Literate Console are missing when using `watch`. If `watch` can sort of forward those colors, it would be really nice

**Comment by natemcmaster** [comment] 2016-11-06 00:48
Can you share repo steps? I couldn't reproduce using dotnet-cli 1.0.0-preview2-003121 and dotnet-watch 1.0.0-preview2-final in Command Prompt and macOS terminal.

```c#
using System;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("\x1B[36m I'm colorful. \x1B[39m");
        }
    }
}
```

![image](https://cloud.githubusercontent.com/assets/2696087/20034582/e878794c-a37f-11e6-9718-ffca4829b7c5.png)

**Comment by natemcmaster** [comment] 2016-12-01 06:18
Closing this for now as we need more information to reproduce the error. We can reopen for more investigation if you can provide steps to reproduce the problem.

Thanks
~Nate

**Closed by natemcmaster** 2016-12-01 06:18 UTC
Labels: dotnet-watch

**Comment by nwykes** [comment] 2016-12-05 19:39
Isn't this https://github.com/dotnet/cli/issues/1977?

code to repro:
```c#
using System;
using System.Threading;
using Serilog;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .WriteTo.LiterateConsole()
                .CreateLogger();

            Log.Information("Hello {Name} from thread {ThreadId}", Environment.GetEnvironmentVariable("USERNAME"),
                Thread.CurrentThread.ManagedThreadId);

            Log.CloseAndFlush();
        }
    }
}
```

`dotnet watch run`

![screen shot 2016-12-05 at 12 37 52 pm](https://cloud.githubusercontent.com/assets/593993/20899437/aed0a10e-bae7-11e6-9234-3e690bfa0c5a.png)

`dotnet run`

![screen shot 2016-12-05 at 12 38 17 pm](https://cloud.githubusercontent.com/assets/593993/20899458/bcf1cbf0-bae7-11e6-8461-f75fdf15698e.png)

**Comment by cormacrelf** [comment] 2016-12-06 05:30
dotnet/cli#1977 looks like it does fix this, but apparently Serilog.Sinks.Literate isn't using ANSI escape codes to do their colours: serilog/serilog-sinks-literate#9. Not a problem with the CLI.
