### ISSUE TITLE
CTRL-C with dotnet watch in Linux or Mac takes 20 to 30 seconds

### ISSUE THREAD

**Issue by MichaelSimons** [aspnet/DotNetTools#410] opened 2018-03-19 21:59 UTC
_Copied from https://github.com/dotnet/dotnet-docker/issues/431 by @richlander_ 

I am running a Docker container per the instructions in #420. CTRL-C works for ASP.NET locally and for console apps in a container but not for ASP.NET apps in a container. I get this same behavior on Windows and macOS.

Command line:

```console
docker run --rm -it -p 8000:80 -v c:\git\dotnet-docker\samples\aspnetapp:/app/ -w /app/aspnetapp microsoft/dotnet-nightly:2.1-sdk dotnet watch run
```

Result:

```console
Hosting environment: Production
Content root path: /app/aspnetapp
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
^CApplication is shutting down...
watch : Shutdown requested. Press Ctrl+C again to force exit.
^C
^C^C^C^C^C^C
^C^C^C^C^C^C^C^C
^C^C^C^C^C
```

/cc @natemcmaster @MichaelSimons @glennc

_Copied from https://github.com/dotnet/dotnet-docker/issues/431#issuecomment-374237841 by @MichaelSimons_

This appears to be tied to using `dotnet watch` in conjunction with ASP.NET.  CTRL-C works as expected when running an ASP.NET app directly within a container.

_Copied from https://github.com/dotnet/dotnet-docker/issues/431#issuecomment-374247175 by @MichaelSimons_

Upon further inspection, CTRL-C is working. It is just extremely slow.

_Copied from https://github.com/dotnet/dotnet-docker/issues/431#issuecomment-374384509 by @richlander_

I just repro'd that. It takes about 20s for me, on both macOS and Windows. Surprisingly, Windows containers don't seem to have this problem.

_Copied from https://github.com/dotnet/dotnet-docker/issues/431#issuecomment-374390354 by @natemcmaster_

I can repro, too. You can move this to aspnet/DotNetTools. I have a hunch it may be something in the "kill process tree" code, but I'm not sure.

**Comment by muratg** [comment] 2018-03-19 23:51
Ugh. cc @glennc

**Comment by muratg** [comment] 2018-04-12 17:53
Moving this out due to scheduling constraints.

**Comment by natemcmaster** [comment] 2018-05-11 20:03
Ok, I've narrowed down the cause to this code: https://github.com/aspnet/Common/blob/e79302c419482487aa26d136d23abc944c5972bf/shared/Microsoft.Extensions.Process.Sources/ProcessHelper.cs#L88-L111. This is the code that attempts to kill a process tree.

From what I can tell, there appears to be some kind of deadlock on the thread pool. On macOS and Linux, ProcessHelper.KillTree attempts to use Process.Start + pgrep to discover the tree of processes. The thread invoking this path deadlocks on Process.WaitForExit(int timeout). The 30 second hang when killing the aspnet process exactly matches the timeout given to WaitForExit.

We should re-examine how we determine the process tree. We may be able to use procfs on Linux, and p/invoke to sysctl on macOS to get the process tree. Ideally, .NET Core would provide an API for this (see https://github.com/dotnet/corefx/issues/26234), but until then, we need to workaround.

**Comment by muratg** [comment] 2018-05-12 00:09
Thanks Nate! So this is not for Docker containers, then?

**Comment by natemcmaster** [comment] 2018-05-12 00:14
It doesn't appear to affect Docker anymore. Also, it doesn't affect Windows.

More details: CTRL+C kills the parent process (dotnet.dll) but leaves dotnet-watch.dll running as an oprhaned process. Docker kills any orphaned process when the container exits. The issue still appears when running in the shell though. You'll still get some console output 30 seconds later from the orphaned dotnet-watch.dll process if you run `dotnet watch --verbose`.

**Comment by muratg** [comment] 2018-05-12 00:28
Got it! Thanks and I updated the title.

**Comment by natemcmaster** [comment] 2018-05-16 00:30
This actually turns out to be a regression in Process.WaitForExit. https://github.com/dotnet/corefx/issues/29699. But I've added a workaround to dotnet-watch for now that should still work when/if https://github.com/dotnet/corefx/issues/29699 is resolved.

**Closed** 2018-05-16 00:29 UTC
Labels: 2 - Working, bug, tool: watch
